import type { Metadata } from "next";
import { type PropsWithChildren } from "react";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import Locale from "intl-locale-textinfo-polyfill";
import localFont from "next/font/local";

import Provider from "@/provider";
import { Box } from "@mui/material";
import "react-toastify/dist/ReactToastify.css";
import "../globals.css";

export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by create next app"
};

const NerkoFont = localFont({
  src: "../../../public/fonts/NerkoOne-Regular.ttf",
  display: "swap",
  weight: "400"
});

export default function RootLayout({
  children,
  params: { locale }
}: PropsWithChildren<{ params: { locale: string } }>) {
  const { direction: dir } = new Locale(locale).textInfo;
  return (
    <html lang={locale} dir={dir}>
      <body
        className={NerkoFont.className}
        style={{
          backgroundColor: "#e2e2e2",
          overflow: "hidden"
        }}
      >
        <AppRouterCacheProvider>
          <Provider locale={locale}>
            <Box
              display="flex"
              mx="auto"
              bgcolor="#FFFFFF"
              maxWidth="450px"
              height="100vh"
              sx={{
                overflow: "hidden",
                overflowY: "scroll",
                "&::-webkit-scrollbar": {
                  width: "4px"
                },
                "&::-webkit-scrollbar-thumb": {
                  backgroundColor: "#0000001f !important"
                }
              }}
            >
              {children}
            </Box>
          </Provider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
